cookie:
  expiry_days: 30
  key: bitcointrends_key
  name: bitcointrends
credentials:
  usernames:
    juandavid7777:
      email: juandavid7777@gmail.com
      name: Juan David Barbosa
      password: $2b$12$.vqJds3I9TTtgcfofCAzy.st.l6RL9.7UAw2MKbWNufLiylrpN1m2
preauthorized:
  emails:
  - esratrepci@gmail.com
  - quajada@hotmail.com
  - n.ram.g@outlook.com
